In [76]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [77]:
bitCoin=pd.read_csv('BitcoinPrice.csv')

In [78]:
bitCoin.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [79]:
bitCoin.tail()

Date         Price
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

In [80]:
bitCoin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [81]:
bitCoin.drop(['Date'],1,inplace=True)

In [82]:
bitCoin.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

# Predicting Bitcoin Price 

In [83]:
Predict_day=30
bitCoin['Predicted']=bitCoin[['Price']].shift(-Predict_day)

In [84]:
bitCoin.head()

Price    Predicted
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [85]:
bitCoin.tail()

Price  Predicted
360  10746.507692        NaN
361  10169.094167        NaN
362  10030.746667        NaN
363  10255.977500        NaN
364  10158.540833        NaN

# Test Train Data Split

In [86]:
X=np.array(bitCoin.drop(['Predicted'],1))

In [87]:
X

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


Removing last 30 day Price Value

In [88]:
X=X[:len(bitCoin)-Predict_day]

In [89]:
X.shape

(335, 1)

In [90]:
y=np.array(bitCoin['Predicted'])

Removing last 30 NaN values

In [91]:
y=y[:-Predict_day]

In [92]:
y.shape

(335,)

In [93]:
from sklearn.model_selection import train_test_split

In [94]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,)

In [95]:
Predict_days_arr=np.array(bitCoin[['Price']])[-Predict_day:]

In [96]:
Predict_days_arr.shape

(30, 1)

In [97]:
from sklearn.ensemble import RandomForestRegressor

In [98]:
Random=RandomForestRegressor(n_estimators=1000,random_state=1)

In [99]:
Random.fit(X_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=1)

In [100]:
print('Random Forest Accuracy:{:2f}%'.format(Random.score(X_test,y_test)*100))

Random Forest Accuracy:85.640303%


# Prediction

In [101]:
Random_Predict=Random.predict(X_test)

In [102]:
Random_Predict

array([ 6326.60075488,  5016.62961974,  4491.4091345 ,  3785.4775425 ,
        3753.19744976,  3683.34840667,  6949.72812   ,  6577.85390533,
        6509.26117133,  3980.77381012,  5257.10223   ,  6579.67292   ,
       10544.44880692,  3635.033345  ,  4377.08587012, 10224.64160917,
        3791.58511417,  7160.41974   ,  3831.8830126 ,  7198.80980667,
        6378.53638981,  9454.31420564,  3822.54153038, 10558.52894   ,
        5512.30396167, 11583.37609096,  7152.66918833,  3737.15186917,
        5353.58692833,  7068.3047125 ,  3696.47669774,  3812.58939976,
        9933.62805417,  8192.6648475 ,  4029.66240583,  3875.8192284 ,
        6449.138565  ,  3900.043605  ,  3778.3586525 ,  3754.89259167,
        5727.996595  ,  8185.1811375 , 11230.24547917,  7309.38508083,
        3875.579625  ,  7855.42207   ,  3832.09848455,  4272.76764917,
        6385.70912141, 10587.77393917,  9150.53426872,  3995.23839737,
        3727.42132167,  4742.45812417,  5866.45663857,  3922.38243417,
      

In [103]:
Prediction_30=Random.predict(Predict_days_arr)

In [104]:
Prediction_30

array([10455.46825167, 10328.88394167, 10351.0132775 , 10284.8799025 ,
       10284.8799025 , 10436.45575083, 10240.856435  , 10288.53416551,
       10141.19919269, 10106.82030186, 10028.40217267, 10871.16639833,
       10051.535796  , 11209.35303333, 10261.7352825 , 11204.15180583,
       11417.430865  , 11417.430865  , 10714.76842833, 10233.20992218,
       10230.56321917, 10103.32053353, 10121.87915436, 10121.87915436,
       10615.82427109, 10142.43093936, 10211.45470833, 10224.64160917,
       10104.22989769, 10235.53696167])

In [105]:
bitCoin.tail()

Price  Predicted
360  10746.507692        NaN
361  10169.094167        NaN
362  10030.746667        NaN
363  10255.977500        NaN
364  10158.540833        NaN

# Appending Predicted Last 30 Days Value , removing NaN

In [106]:
bitCoin['Predicted'][-30:]=Prediction_30

In [107]:
bitCoin.tail(31)

Price     Predicted
334  10021.325000  10158.540833
335   9774.257500  10455.468252
336   9725.402500  10328.883942
337   9500.324167  10351.013277
338   9533.979333  10284.879902
339   9539.712500  10284.879902
340   9873.811667  10436.455751
341  10088.800000  10240.856435
342  10478.901667  10288.534166
343  10790.630000  10141.199193
344  10826.275000  10106.820302
345  11713.161667  10028.402173
346  11759.019167  10871.166398
347  11703.738333  10051.535796
348  11803.888333  11209.353033
349  11816.912500  10261.735282
350  11586.172500  11204.151806
351  11377.804167  11417.430865
352  11397.801667  11417.430865
353  11144.389167  10714.768428
354  10450.813333  10233.209922
355   9988.947500  10230.563219
356  10230.733333  10103.320534
357  10292.383333  10121.879154
358  10295.117500  10121.879154
359  10605.825833  10615.824271
360  10746.507692  10142.430939
361  10169.094167  10211.454708
362  10030.746667  10224.641609
363  10255.977500  10104.229898
364  10158.540833  10235.536962